### ISSUE TITLE
Resize side panel elements (accordion)

### ISSUE THREAD

**Issue by linuxenko** [cs01/gdbgui#100]
Hi :unicorn: 

First of all i'd say it is really cool tool  i like it. But the feature i most wanted does not work properly for me :cry: 

I unable to resize the `tree view` pane

[![tree view pane](http://i.imgur.com/0rBR7D1.png)](http://i.imgur.com/0rBR7D1.png)

Help !! ))

**Comment by cs01** [comment]
It should be possible to use your scroll wheel to zoom in/out of the tree viewer.

**Comment by linuxenko** [comment]
It is not so cool see the image inside of so small pane... What do you think about small button/link on the title `tree view` for an instance `new window` or `open in new window`, or `copy image url`, something like this ? Just base64 url of the rendered image.

**Comment by cs01** [comment]
Cool idea. Sounds like there are a few options:

- Button to pop out into new window
- Button to download png of the graph
- Buttons to expand/contract the size of the graph view area 

Is that correct? I think I prefer the button to expand/contract the size of the graph view. Popping into a new window might make things a little too complicated because there can be several tabs open, each with their own gdb process, so determining which window corresponds to which tab might be hard. 

> offtopic, grassfedcode is it your irc nickname ? i've seen the link to this project at #gdb channel

Yes that's me! Hope you like the tool. If you do, spread the word :)
