### ISSUE TITLE
How to integrate it with cargo build system

### ISSUE THREAD

**Issue by adrianbrink** [cs01/gdbgui#113]
I am honestly a complete beginner at using gdb. I have managed to get it to work by using rustc directly, but it doesn't offer the best experience.

What options do I have to give to cargo or in the Cargo.toml file in order to produce output that is compatible with gdbgui?

Btw, this is awesome.

**Comment by cs01** [comment]
> What options do I have to give to cargo or in the Cargo.toml file in order to produce output that is compatible with gdbgui?

It looks like you can set `debug=true` in your profile. See http://doc.crates.io/manifest.html#the-profile-sections, and https://stackoverflow.com/questions/38803760/how-to-get-a-release-build-with-debugging-information-when-using-cargo.

If you get it working better, can you submit a PR to update the Rust example?

Glad you are liking it :smiley:

**Comment by PhilipDaniels** [comment]
Found this issue while trying gdbgui with Rust. Programs built in debug mode (i.e. a standard `cargo build`) include the relevant debugging symbols by default, so that isn't a problem.

I also followed the two hacks here https://github.com/rust-lang/rust/issues/33159 (edit the py script, create a .gdbinit) to avoid a warning about not being able to load files at gdbgui startup. 

After that, gdbgui was warning about not being able to find "main". To work around that, I just typed 'main' in the file browser, gdbgui found my main.rs and I could place a breakpoint with the mouse and start the program.

So with a small bit of one time setup, it seems to be working nice.

Do you think there is any way gdbgui could auto-detect that it is dealing with a Rust program to avoid the 'main' warning?

**Comment by cs01** [comment]
> Do you think there is any way gdbgui could auto-detect that it is dealing with a Rust program to avoid the 'main' warning?

Yes, it could run the command `show language` then parse its output (I don't know of a gdb machine interface command). And then I assume if the language is rust or go (which also has this issue), then you think it would be helpful if gdbgui would print a warning saying `breakpoint will not be added because language is rust`. LMK if that sounds good and I can put it on my TODO list.

More details on why this happens: gdbgui runs the gdb command `-break-insert main`, and then gets a breakpoint from gdb. The breakpoint has a field called `fullfile` which is usually a path to a file, but in this case gdb cannot find the function and/or file and it just puts a breakpoint at an address. So the `fullfile` file is just called main, and then gdbgui tries to open it and it fails.

**Comment by PhilipDaniels** [comment]
Immediately after starting gdbgui with my little Rust program, entering `show language` displays

    The current source language is "auto; currently c"

so I am not sure that helps. 

Here is the user story at the moment for Rust. After starting gdbgui, you are confronted with a blank screen which is a bit intimidating, especially for a newbie like me who is trying to use your program in order to avoid having to really learn gdb (typical Visual Studio refugee...):

![gdbgui1](https://user-images.githubusercontent.com/1809220/39269379-8ead9400-48ca-11e8-9530-1e85fe97a3a9.png)

If you then type `main.rs` in the box at the left you get auto-completion so it is not too difficult:

![gdbgui2](https://user-images.githubusercontent.com/1809220/39269390-952fce06-48ca-11e8-84d9-6e56d6f75a25.png)

The main.rs file is then displayed and you can place the breakpoint with a simple mouse click.

![gdbgui3](https://user-images.githubusercontent.com/1809220/39269396-9a7d6b20-48ca-11e8-9be0-4e2413bd2cd7.png)


So the best solution, if you can detect Rust, would be to automate those steps. Failing that, I think just adding those steps to the https://gdbgui.com/docs.html or https://gdbgui.com/examples.html page would be a great help. Perhaps under a specific "Debugging Rust programs" heading.

If you think improving the docs is the way to go let me know where you would like it to go and I will submit a PR.

**Comment by cs01** [comment]
Thanks for the user story! And good to know the program is intimidating. I will add some helpers (that can be dismissed).

When you ran `show language`, had you already loaded your rust binary? I ask because it did show rust for me when I ran it after loading a binary (but C before launching anything). So I can add the check after a binary is loaded if it works for you.

> So the best solution, if you can detect Rust, would be to automate those steps. 

Agreed, but I'm afraid the only reason typing `main` worked for you is because you have a file named `main`, not a function with that name. What I could do is automate the opening of the side panel and adding a tooltip that says "enter filename" or something. 

> If you think improving the docs is the way to go let me know where you would like it to go and I will submit a PR.

I think a good spot for this would be a new section called "Debugging Programs Written in Rust or Go" just before "Running gdbgui Remotely".

**Comment by PhilipDaniels** [comment]
I ran `show language` immediately after running `gdbgui target/debug/myprog`. If I wait until it hits the breakpoint I set in main then `show language` prints `auto; currently minimal`. Maybe we have different environments, I am running the latest nightly Rust build on Linux.

Re main.rs, I have this file because I created my program with `cargo new blah` and it creates this file for you as part of the skeleton app. I reckon approx. 99% of Rust users will do the same. Cargo is very embedded in the Rust ecosystem now, your examples are the only place I have ever seen makefiles. So if you are going to open the side panel, it would probably be a good idea to pre-populate it with "main.rs". One caveat is that there are such things as multi-program workspaces so there may be more than one main.rs on disk, I don't know how you build the file list so I don't know whether that would be a problem.

I'll take a bash at the PR this weekend.

**Comment by cs01** [comment]
Cool, thanks. Also, as you may have guessed from the makefile, I don't use Rust. So if you want to make the Rust example better with more standard cargo workflow that would probably make more sense to Rust users seeing gdbgui for the first time. If not that's fine too. Thanks for all your input either way.
