### ISSUE TITLE
Fixed height of panels in right side bar

### ISSUE THREAD

**Issue by bobthekingofegypt** [cs01/gdbgui#135]
This is kind of a possible enhancement discussion about fixing the height of threads, breakpoints etc in the right side bar.

Currently I've been debugging servo and it can have anything from one a lot of threads during parallel execution, this causes the threads section of the sidebar to be huge and the variables section to keep jumping around.  I was wondering what other people thought about fixing the height of each section on the sidebar and setting their overflow to scroll so they all scroll independently.

**Comment by cs01** [comment]
Glad to hear you got servo working under gdbgui.

Personally, I don't like the sections being fixed width because I inevitably end up resizing them almost every time I want to interact with them, and that quickly gets tedious. If I have a large, dynamic call stack I usually collapse it. Have you tried that? Another datapoint: Chrome and Firefox don't allow resizing of the sidebar in their debuggers.

**Comment by bobthekingofegypt** [comment]
No worries, it's a bit of a personal preference thing.  I'm used to the big IDE's and how their gui's are laid out,  I like to have at least the top of the current call stack and variables visible at the same time.

**Comment by cs01** [comment]
Any other new thoughts on the topic? If you want to add a setting to freeze the side panel I would be fine with that, but am not really able to take it on myself.

**Comment by bobthekingofegypt** [comment]
I'm currently just running on a completely custom build as I mess with things to a state where I'm happy.  I don't believe my current version will ever be suitable to merge in.  

I'll close this for now.

**Comment by cs01** [comment]
Hey @bobthekingofegypt, this was requested in another ticket (https://github.com/cs01/gdbgui/issues/162) so I added it in gdbgui v0.10.3.0. LMK what you think.
