### ISSUE TITLE
windows users: what has been your experience with gdbgui?

### ISSUE THREAD

**Issue by cs01** [cs01/gdbgui#149]
Since I'm not a Windows user, I rely on user feedback regarding gdbgui compatibility. In general, I don't really see why gdb would be used on windows since it's oriented toward linux. Can it even be used without some sort of unix emulation (such as cygwin)?

The following questions are of interest:
- Are you happy with gdbgui's workflow on Windows?
- Do the installation instructions work as written for Windows?
- Do you use native Windows or some sort of emulation layer/library?
- Which version(s) of Windows do you use?

Thanks!

**Comment by dimpurr** [comment]
When I try to open a file, it always report like this: `file not found: /c/Users/myccy/Documents/Codes/ACM/CodeVS/1978.cpp`
I had tried it in Chrome/Edge Browser, or run gdbgui in Cygwin (git bash) / PowerShell.

What should I do?

**Comment by cs01** [comment]
@dimpurr , glad you got it working! 

> Hope it can be used without unix emulation soon!

How were you using it before you upgraded Cygwin? With an old version of Cygwin, MinGW, or something else?

**Comment by dimpurr** [comment]
@cs01 Yeah, I'd tried Cygwin (old version), git bash, PowerShell, CMD.
All can run the server, but the file path can't work normally. (CMD/Power Shell default use path like `C:/User/...` , Git Bash default use `/c/User/...` , but it can't works.)
And after I upgraded Cygwin, it (file path bar in the top of the page) only work properly in Cygwin. (Use `/c/User/...` )

**Comment by cs01** [comment]
@dimpurr I looked into this and made some changes. gdbgui should now work with with MinGW in cmd/powershell. There is also a windows binary available at [gdbgui.com](http://gdbgui.com).

**Comment by gggin** [comment]
I do not know about cygwin and mingW, but I want to use this for cl.exe(Visual Stduio) compiled executable, maybe a new debug protocol or some way.

**Comment by sepavel** [comment]
I have compiled PIVX project using mingw in debug mode on Windows 10 x64. 
Paths format to source files is "/mnt/c/<path-to-project".

Gdbgui reports "File not found: /mnt/c/PIVX/src/qt/pivx.cpp". 
I have tried to start it from cmd and from bash on linux subsystem on windows

Any advice?

**Comment by NarniaT** [comment]
Thanks for this interesting software, however, I can not use it on Windows. I'm using gcc on WSL and as a result I don't get .exe files after compilation, but gdbgui asks for exe files.

**Comment by orazdow** [comment]
I use Mingw on widows since I prefer that build system. I have the same problem @dimpurr mentioned, that I cannot load source files in the gui.

Specifically what happens is this: "fetch source files" works, and lists the correct source files, but loading a source file fails. 

So the source file `C:\Users\ollie\Documents\spark\Sl_temp\soundlib.h` is listed correctly, but clicking to load (or pasting in the path) results in the error: 
`file not found: /C:\Users\ollie\Documents\spark\Sl_temp\soundlib.h`

**Comment by MySurmise** [comment]
I am using gdbgui with WSL and a GUI Tool called "GWSL". When I try to access it in my Windows browser, it doesn't work. I also installed firefox on WSL and ran it there, but that didn't work either. Compiled with gcc. It does show the Dashboard though, in both browsers, so that connection seems to work It just can't access the filesystem, maybe?

**Comment by MySurmise** [comment]
I tried to open gdb in the dashboard with the command "gdb <filepath>". Now it just opens a gdb session, crashes immediately and opens a new session. It opened and closed 150 sessions in the last 2 minutes.

**Comment by MySurmise** [comment]
nvm gdb wasn't installed xD
Still leaving this here, maybe you should also display this, even if it's a dumb mistake, sorry.

**Comment by gpdzvapatsva** [comment]
When I try to run gdbgui on my windows it generates the following error:
   raise RuntimeError(
RuntimeError: Windows is not supported at this time. Versions lower than 0.14.x. are Windows compatible.
Please help. I cloned the gdbgui fro github
