### ISSUE TITLE
[error] Variable object not found

### ISSUE THREAD

**Issue by harumo11** [cs01/gdbgui#16]
Hello @cs01 
Thanks cool debugger!

I get following error when I try to look vector's inside.

<img src="https://7sfu3q-ch3302.files.1drv.com/y3m2IxwxowAhGiKQmVdStUP2dithoKlN9MbZ65PJGp9r88_AEeA8uFMh0-cqILTCUG5EcWtjA6Y0A9DaFubd1p40qcPXhGWhQPZwvWUpBiaCwoATRalzUuvncaOH928Q62sYEXnJ2pAZxTuA7nLXnj4BpiinADO7VPCTLkTLgRkClk?width=1855&height=1056&cropmode=none" width="1855" height="1056" />

My environment is as below.

| OS | Web browser |
|:----:|:-----------------:|
| Ubuntu 16.04 | Firefox |

When I debug following program for now.

```c++
#include <iostream>
#include <vector>

using namespace std;

int main(void)
{
    vector<char> str;
    vector<double> pos(3);
    vector<char> a(10,'a');
    vector<double> d {1.1, 2.2, 3.3, 4.4};
    vector<double> cop(d);

    for(auto itr = begin(d); itr != end(d); ++itr)
    {
        cout << *itr << "\t";
        *itr += 10;
    }
    cout << endl;
    
    for(auto itr = begin(d); itr != end(d); ++itr)
    {
        cout << *itr << "\t";
    }
    cout << endl;

    return 0;
}
```

Then I compiled and run following command to launch gdbgui

    $ g++ -std=c++11 vector.cpp
    $ gdbgui ./a.out

And tried to d vector's inside. But I got error.
Could you tell me what I make a mistake?

Thanks in advance.

**Comment by cs01** [comment]
Thank you for the detailed issue. I recreated it and fixed it. Version 0.7.4.0 has the fix. Please submit any other issues you encounter so I can make the tool better for everyone. By the way, in v0.7.4.0 you can now click variables in the "Locals" section to view their fields, instead of manually creating Expressions.

In case you are interested in the source of the problem, there were two issues. The first was that gdbgui was not wrapping variable expressions in quotes, so gdb attempted to evaluate an invalid expression (which was the error you were getting).

Even after that was fixed, the information returned by gdb was pretty useless. It described some internal methods to c++ vectors. To make this output more useful, I added the ` -enable-pretty-printing` option by default, which gdb has had since gdb version 7.0. It can be changed in the Settings section (gear on top right of gdbgui).

With pretty printing (gdbgui's new default):
![image](https://cloud.githubusercontent.com/assets/5715368/23414920/69e87ea2-fd92-11e6-9769-76f5c9cbda85.png)

Without pretty printing (option can be selected in Setting):
![image](https://cloud.githubusercontent.com/assets/5715368/23414979/9ac997ea-fd92-11e6-9a83-3ebf7d09ace6.png)
