### ISSUE TITLE
Undefined MI command: data-read-memory-bytes

### ISSUE THREAD

**Issue by emmett-b** [cs01/gdbgui#161]
##### Describe the issue
I get a lot of "Undefined MI command: data-read-memory-bytes" errors in the console, seemingly preventing proper call stack display.

##### Steps to replicate
Attach to a process, select a thread.

##### Describe your environment
* Operating system and version: RHEL 6.9
* gdbgui version (`gdbgui -v`): 0.10.2.0
* gdb version (`gdb -v`): GNU gdb (GDB) Red Hat Enterprise Linux (7.2-92.el6)
* browser: Firefox 52.5.1
* python packages (`pip freeze`): 
click==6.7
Flask==0.12.2
Flask-Compress==1.4.0
Flask-SocketIO==2.9.3
gdbgui==0.10.2.0
gevent==1.2.2
greenlet==0.4.12
itsdangerous==0.24
Jinja2==2.10
MarkupSafe==1.0
pygdbmi==0.8.2.0
Pygments==2.2.0
python-engineio==2.0.2
python-socketio==1.8.4
six==1.11.0
virtualenv==15.1.0
Werkzeug==0.14.1

**Comment by cs01** [comment]
I have never tested with a gdb version earlier than 7.6, so this might be the cause of the issue. Are you trying to view memory in gdbgui? I don't _think_ it should have any impact on call stack display since gdbgui handles memory responses completely independently from call stack responses.

Could you send a screenshot of the error or copy+paste the exact error message?

**Comment by emmett-b** [comment]
I updated my gdb, and now I have other issues, so I'll submit a new issue if needed.
Feel free to close/delete this.
Thank you!

**Comment by cs01** [comment]
My pleasure. Are the other issues gdb issues or gdbgui issues?

**Comment by emmett-b** [comment]
I don't really know, I didn't have time to look into this. Probably issues with me ;)
