### ISSUE TITLE
gdbgui doesnt work with rr

### ISSUE THREAD

**Issue by neerajbadlani** [cs01/gdbgui#179]
##### Describe the issue
gdbgui goes into a loop and doesnt work as expected with rr

##### Steps to replicate

* Step 1 : rr record <binary>
* Step 2 : gdbgui --port 8080 --host localhost --rr -r

* Screenshot of the Loop output 
![screen shot 2018-03-01 at 2 02 08 pm](https://user-images.githubusercontent.com/3440085/36883393-c2a11744-1d8e-11e8-817e-1ee772c22316.jpeg)

**Comment by cs01** [comment]
Did you set any break points in the program? Can you provide more details into what you did to reproduce this or did it just start happening on its own after the browser opened it?

**Comment by neerajbadlani** [comment]
1. Nope , no breakpoints , rr record <binary> 
2. Execution finishes with rr record without any issues , able to use rr replay on command line without any issues.
3. Open browser ( after gdbgui --port 8080 --host <remotehost> --rr -r ) and as soon as browser is opened , it goes into loop mentioned above , without me doing anything ( this is not browser specific)

**Comment by cs01** [comment]
I see two reasons this could be happening:
1. gdbgui is sending some commands behind the scenes that are causing the error
2. gdbgui invokes rr with the "mi2" interpreter and exercises different code paths or rr by invoking mi commands 

To test the first:
* run gdbgui, open settings (gear icon in top right)
* check the box `Print all sent commands in console, including those sent automatically by gdbgui`
* re-run RR and see if anything looks suspicious. Copy a screenshot to here because if there is a bug that will definitely help me fix it.

It might also be that when gdbgui tries to insert a breakpoint at main automatically (can be configured in Settings > `Add breakpoint to main after loading executable`), that causes RR to segfault for your setup since maybe you don't have a `main` function?


If that doesn't yield any results, you can test the second theory. Try running rr from the terminal with `rr -i=mi2`, then running the same commands gdbgui runs and see if it segfaults.

**Comment by neerajbadlani** [comment]
So the issue seems to be "1-data-evaluate-expression fflush(0)" sent by gdbgui.

![screen shot 2018-03-02 at 4 04 30 pm](https://user-images.githubusercontent.com/3440085/36927618-70fb83e8-1e33-11e8-9b4a-8369858279d3.jpeg)


Let me know if there is anything else you need

**Comment by cs01** [comment]
I updated the master branch which adds an option in the settings pane to not send the fflush command. Let me know how that works for you. If it's good I'll create a new release.

**Comment by neerajbadlani** [comment]
Works now ! Thanks a lot
