### ISSUE TITLE
Support for Python debugger

### ISSUE THREAD

**Issue by Photonios** [cs01/gdbgui#22]
I've thought a long time of building something like this for the Python debugger. I'd love to contribute support for that to this raher than building yet another project that does half of what this one does.

Would you be open to a contribution like this?

**Comment by cs01** [comment]
I was actually thinking about that as I was making gdbgui, since I was using `ipdb` to debug the backend. Here are my thoughts.

* It would be a fun challenge, and educational for me, to write a debugger for python
* It would overlap, but not entirely, with the frontend code that exists for gdb
* There already exists a really good graphical debugger (pycharm) that is free

I think there would be enough differences between the two that it would make development of gdbgui kind of cumbersome and difficult to maintain. Anyone who wants to make a change would have to understand how both debuggers work in detail, and code around their differences. 

If it's something that sounds fun to you, I would suggest forking gdbgui and making a new project such as `pywebdebugger` (I'm not too creative with names :)). It's better to make tools that "do one thing and do it well", so while I appreciate the suggestion, I don't think it's something I would like to move forward on. Looking forward to using `pywebdebugger` though!

**Comment by balta2ar** [comment]
@Photonios Just FYI, there is a web debugger for Python already: https://github.com/Kozea/wdb
Of course I'm not telling you what to do, but it might be a good idea stay focused [on C/C++, Go, Rust] and do less things better. Just saying.
