### ISSUE TITLE
Error occurred on server when running gdb command : gdb is not running

### ISSUE THREAD

**Issue by ORCA666** [cs01/gdbgui#397]
### hey, so i did the following:

![2222222](https://user-images.githubusercontent.com/66519611/122911729-430a4600-d360-11eb-8b9c-c67b81c88ec2.png)

### and as i saw in [here](https://www.youtube.com/watch?v=Cd0BOOdGjrw) no more steps were executed, so i went to my browser and ...

![1111111](https://user-images.githubusercontent.com/66519611/122911996-8c5a9580-d360-11eb-98b3-9f7ad27677a7.png)

### and thanks for this code !

**Comment by misutoneko** [comment]
There's some sort of version mismatch going on.

gdbgui_0.14.0.2 gives a bit more detailed info, it says:
gdb: /tmp/_MEIIvNnDO/libtinfo.so.6: version `NCURSES6_TINFO_6.2.current' not found (required by /lib/x86_64-linux-gnu/libncursesw.so.6)

So I guess that's because Kali is using rolling release model?
You can try replacing the libraries libtinfo.so.6.2 and libncursesw.so.6.2 with ones that don't have that "current" reference (for example, ones from Ubuntu/Mint). Or perhaps they can be LD_PRELOADed (to avoid causing a mess with the rest of the system).

**Comment by cs01** [comment]
You might want to just download gdb or build from source https://www.gnu.org/software/gdb/download/

**Comment by hffaust** [comment]
Had this same issue in Debian 11 :/
